REFACTOR: Update SignUp page with new inputs component #30
TremboBoys/Freela_Frontend pull request #34
Opened 2024-09-09 19:25 UTC by GuilhermeSchreiber7

2024-09-10 13:26 UTC, LuizBlume requested changes
adjust components

2024-09-10 13:47 UTC, Joaovictor23t4 requested changes
Read the comments!

2024-09-10 13:47 UTC, Joaovictor23t4 commented on src/components/SignUp/SignUpInputs.vue
Mudar o nome da pasta de SignUp para `signUp`.

Criar uma pasta `inputs` dentro de `signUp` e dentro dela criar mais 3 componentes: InputTextSignUp, InputEmailSignUp, InputPasswordSignUp. Deixar escrito nos 3 inputs: class:"form-control" e aria-describedby="nameHelp".

Passar por props: o texto do label e o id do input (que será o mesmo valor para a propriedade "for" do label).

Remover da class do label o 'name, user, email e password' e deixe somente o labelInput.

2024-09-13 16:58 UTC, Joaovictor23t4 approved these changes
OK!

2024-09-13 17:01 UTC, LuizBlume approved these changes

2024-09-13 17:01 UTC, merged